# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: reusable_test

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  core-and-tasklist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: use node ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - run: npm ci
      
      - name: test backend
        run: cd core && npm test

      - name: test "sap tasklist" rendering
        run: |
          cd fiori-app
          npm run test:e2e          

      - name: Upload screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: e2e-screenshots-${{ inputs.node-version }}
          path: fiori-app/webapp/test/e2e/__screenshots__