# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: reusable_test

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  test-core:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: use node ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - run: npm ci
      
      - name: test backend
        run: cd core && npm test

      - name: test "sap" tasklist rendering
        run: |
          cd fiori-app
          npm run test:e2e          
