# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-core:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23, 22, 21]

    steps:
      - uses: actions/checkout@v4
      - name: use node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: cd core && npm test