# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/reusable_test.yml
    with:
      node-version: ${{ matrix.node-version }}

    strategy:
      matrix:
        node-version: [23, 22, 21]